---
title: "AtSphere Screen tree"
subtitle: "Thoenen_et_al_Bacteria_BX_metabolization"
author: "Lisa Thönen"
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_caption: yes
    toc: true
    toc_float: true
    theme: cerulean
    code_folding: show
editor_options: 
  chunk_output_type: console
---

Here we plot the results of the MBOA to AMPO screen AtSphere bacteria using the plate assay.
 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
rm(list=ls())
```

```{r,include=FALSE}
# install.packages("dplyr")
# install.packages("plyr")
# install.packages("magrittr")
# install.packages("ggplot2")
# install.packages("readxl")
# install.packages("readr")
# install.packages("stringr")
# install.packages("ggplot2")
# install.packages("forcats")
# install.packages("ggpmisc")
# install.packages("pander")
# install.packages("tidyr")
# install.packages("tibble")
# install.packages("RColorBrewer")
# install.packages("pheatmap")
# install.packages("ggdendro")
# install.packages("reshape2")
# install.packages("grid")
# install.packages("ape")
# install.packages("ggtree")
# install.packages("aplot")
# install.packages("wesanderson")
# install.packages("ggsci")
# install.packages("ggnewscale")
# install.packages("data.tree") # as.Node()
# install.packages("networkD3") # radialNetwork
# install.packages("Cairo")
```

```{r, warning=F, echo=F, message=F}
# ggtree package

# if (!requireNamespace("BiocManager", quietly = TRUE))
#      install.packages("BiocManager")
# 
# BiocManager::install("ggtree")
# #
#
```

```{r,include=FALSE}
library("dplyr")
library("plyr")
library("magrittr")
library("ggplot2")
library("readxl")
library("readr")
library("stringr")
library("ggplot2")
library("forcats")
library("ggpmisc")
library("pander")
library("tidyr")
library("tibble")
library("RColorBrewer")
library("pheatmap")
library("ggdendro")
library("reshape2")
library("grid")
library("ape")
library("ggtree")
library("aplot")
library("wesanderson")
library("ggsci")
library("ggnewscale")
library("data.tree") # as.Node()
library("networkD3") # radialNetwork
library("Cairo")

# load functions
# source("functions/vennDia.R")
# source("functions/fun_venn_plot.R")
# source("functions/fun_venn_pair.R")
# source("functions/fun_venn_triple.R")
```

```{r, warning=F, echo=F, message=F}
database <- readxl::read_excel("Input/AtSphere_AMPOformation.xlsx", sheet = 2)
```

```{r, warning=F, echo=F, message=F}
# scales::show_col(calc_pal()(12))
# database %<>% na.omit()

database$cols_Family <- as.character(database$Family)

database$Family <- gsub("Chitinophagales", "Chitinophagaceae", database$Family)
database$Family <- gsub("Pseudomonadales", "Pseudomonadaceae", database$Family)

database[database$Family=="Bacillaceae" , ]$cols_Family <- "#004586" # "Bacillaceae" 
# database[database$Family=="Chitinophagaceae" , ]$cols_Family <- "#ff420e"
database[database$Family=="Enterobacteriaceae" , ]$cols_Family <- "#ffd320"
database[database$Family=="Erwiniaceae" , ]$cols_Family <- "#579d1c"
database[database$Family=="Microbacteriaceae" , ]$cols_Family <- "#7e0021" # "Microbacteriaceae"
database[database$Family=="Micrococcaceae" , ]$cols_Family <- "#83caff" # "Micrococcaceae"
database[database$Family=="Nocardioidaceae" , ]$cols_Family <- "#314004" # "Nocardioidaceae"
database[database$Family=="Nocardiaceae" , ]$cols_Family <- "#314004" # "Nocardiaceae"
database[database$Family=="Oxalobacteraceae" , ]$cols_Family <- "#aecf00"
database[database$Family=="Pseudomonadaceae" , ]$cols_Family <- "#4b1f6f" # "Pseudomonadaceae"
database[database$Family=="Rhizobiaceae", ]$cols_Family <- "#ff950e" # "Rhizobiaceae"
database[database$Family=="Sphingomonadaceae", ]$cols_Family <- "#c5000b"
database[database$Family=="Xanthomonadaceae", ]$cols_Family <- "#0084d1" # Xanthomonadaceae"

database[database$Family=="Streptomycetaceae" , ]$cols_Family <- "#8b995a"
database[database$Family=="Flavobacteriaceae" , ]$cols_Family <- "#F0D5B4"
database[database$Family=="Paenibacillaceae" , ]$cols_Family <- "#8f9ec9"
# database[database$Family=="Planococcaceae", ]$cols_Family <- "#7F5757"
database[database$Family=="Moraxellaceae", ]$cols_Family <- "#a73e62" # "Moraxellaceae"
database[database$Family=="Sphingobacteriaceae", ]$cols_Family <- "#c75536"
# database[database$Family=="Deinococcaceae", ]$cols_Family <- "#031e33"

database[database$Family=="Burkholderiaceae", ]$cols_Family <- "#cca100" # "Burkholderiaceae" 
database[database$Family=="Comamonadaceae", ]$cols_Family <- "#ffc99f" # "Comamonadaceae" 
database[database$Family=="Bradyrhizobiaceae", ]$cols_Family <- "#4a6731" # "Bradyrhizobiaceae" 
database[database$Family=="Phyllobacteriaceae", ]$cols_Family <- "#8fc4c9" # "Phyllobacteriaceae" 
database[database$Family=="Alcaligenaceae", ]$cols_Family <- "#6eb17c" # "Alcaligenaceae" 
database[database$Family=="Boseaceae", ]$cols_Family <- "#a7a174" # "Boseaceae" 
database[database$Family=="Caulobacteraceae", ]$cols_Family <- "#d67c74" # "Caulobacteraceae" 
database[database$Family=="Cellulomonadaceae", ]$cols_Family <- "#775eb0" # "Cellulomonadaceae" 
database[database$Family=="Devosiaceae", ]$cols_Family <- "#e34738" # "Devosiaceae" 
database[database$Family=="Hyphomicrobiaceae", ]$cols_Family <- "#a042b1" # "Hyphomicrobiaceae" 
database[database$Family=="Intrasporangiaceae", ]$cols_Family <- "#5b8841" # "Intrasporangiaceae" 
database[database$Family=="Mycobacteriaceae", ]$cols_Family <- "#c57319" # "Mycobacteriaceae"
database[database$Family=="Nocardiaceae", ]$cols_Family <- "#297d9b" # "Nocardiaceae"
database[database$Family=="Promicromonosporaceae", ]$cols_Family <- "#86534c" # "Promicromonosporaceae"

# database[ database$Family==NA, ]$cols_Family <- "dimgrey"
# table(database$cols_Family)

## collapsed color vector for each level
temp <- data.frame(database$Family, database$cols_Family)
temp <- plyr::ddply(temp, .variables="database.cols_Family", .fun=unique)   #library(plyr)
database_level_cols_Family <- as.character(temp[,2])
names(database_level_cols_Family) <- temp[,1]
```

# Raw tree

```{r, warning=F, echo=F, message=F, fig.width=15, fig.height=12}
### Newick tree ###
Tree_16s_unique <- ape::read.tree("Input/230816_tree_AtSphere_tested_strains.txt")

plot(Tree_16s_unique, type="fan")

ptree <- Tree_16s_unique %>%
  ggtree(aes(x =0.1), branch.length = "branch.length", ladderize = FALSE, layout = "circular") +
    geom_tiplab(size=3)
ptree
```

compare strains in tree with strains in metadata 
```{r, warning=F, echo=F, message=F, include=F}
strains_tree <- Tree_16s_unique$tip.label %>% unique() %>% as.data.frame()

strains_metadata <- database$Strain %>% unique() %>% as.data.frame()

setdiff(strains_metadata$., strains_tree$.)
```

# Tree with taxonomy annotation

```{r, warning=F, echo=F, message=F, fig.width=15, fig.height=12}
database_Strain_Family <- database %>% filter(!Family %in% NA) %>% dplyr::select(Strain, Family) 

tree_family_branch_line <- ggtree::ggtree(Tree_16s_unique, branch.length = "branch.length", ladderize = TRUE, layout = "circular") %<+% database_Strain_Family+
  geom_tippoint(aes(color=Family), size = 2) + 
  geom_tiplab(align=TRUE, linetype='dashed', linesize=.3, size = 3, offset = 0.1) + 
  geom_treescale(x=0.7, y=-1.9, fontsize=3, linesize=1, offset=1)+
  scale_color_manual(values = database_level_cols_Family)

tree_family_branch_line
```

# Tree with taxonomy and metadata annotation

```{r, warning=F, echo=F, message=F, fig.width=15, fig.height=12}
fIG2.pAMPO_AtSphere <- gheatmap(tree_family_branch_line + new_scale_fill(),
         database %>% 
         dplyr::select(Strain, AMPO_former) %>% 
         distinct() %>% na.omit() %>% 
         as.data.frame() %>% column_to_rownames("Strain") ,
         offset=0.4, 
         width=.1,
         colnames = FALSE,
         colnames_angle= 90, colnames_offset_y = 1, colnames_position="top", font.size=2) + 
         scale_fill_manual(values = c("lightgoldenrod",  "darkred", "tomato1", "white"), name="Color on MBOA")

fIG2.pAMPO_AtSphere

# ggsave(plot = fIG2.pAMPO_AtSphere, filename = "fIG2.pAMPO_AtSphere.pdf", width = 20, height = 20, dpi = 300, scale = 1, units = "cm")
# # 
# ggsave(plot = fIG2.pAMPO_AtSphere, filename = "fIG2.pAMPO_AtSphere.svg", width = 20, height = 20, dpi = 300, scale = 1, units = "cm")
```

```{r, warning=F, echo=F, message=F}
database %>% filter(Strain %in% c("LRC7.0", "Root70", "Root9",  "LSP13",  "Root1280", "Root278", "Root558", "Root239", "Root142", "NBC", "Root423", "Root1312",  "Root74", "Root630", "Root562", "LAC11",  "LMB2",   "Root131", "Root258", "Root919", "Root71", "Root65", "Root635", "Root231", "Root482", "Root1252")) %>% dplyr::select(Strain, Genus, Family, Phylum,AMPO_former)

Strains <- database %>% filter(Strain %in% c("LRC7.0", "Root70", "Root9",  "LSP13",  "Root1280", "Root278", "Root558", "Root239", "Root142", "NBC", "Root423", "Root1312",  "Root74", "Root630", "Root562", "LAC11",  "LMB2",   "Root131", "Root258", "Root919", "Root71", "Root65", "Root635", "Root231", "Root482", "Root1252")) %>% dplyr::select(Strain, Genus, AMPO_former)

Strains_info_text <- toString(t(Strains)) %>% replace(",", "-")

```

```{r, warning=F, echo=F, message=F}
sessionInfo()
```

