---
title: "3strains_anaerobic"
author: "Lisa Thönen"
date: "3/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include=FALSE}
rm(list=ls())
```

```{r,include=FALSE}
# install.packages("dplyr")
# install.packages("magrittr")
# install.packages("tidyr")
# install.packages("stringr")
# install.packages("ggpubr")

# install.packages("readxl")
# install.packages("pander")
# install.packages("ggplot2")

# install.packages("multcomp")
# install.packages("multcompView")
# install.packages("emmeans")
# install.packages("forcats")
# install.packages('tinytex')
```

```{r libraries, echo=F, message=F, warning=F}
library("dplyr")
library("magrittr")
library("tidyr")
library("stringr")
library("ggpubr")
library("readxl")
library("pander")
library("ggplot2")
library("multcomp")
library("multcompView")
library("emmeans")
library("forcats")
```

```{r functions, echo=F, message=F, warning=F}
give.n <- function(x){
  return(c(y = median(x)*1.05, label = length(x))) 
  # experiment with the multiplier to find the perfect position
}
```

# Data 3 days bacterial growth 
```{r, warning=F, echo=F, message=F, include=F}
data <- readxl::read_excel("Input/Sphingo_anaerob.xlsx", sheet = 4)
data %>% colnames()

data %>% typeof()
data <- data %>% as.data.frame()

data$Name <- interaction(data$Strain, data$Treatment, data$Condition, data$Replicate, sep = "_")


```


```{r echo=F, message=FALSE, warning=FALSE}
anaerobicBacFigS.10 <- data %>% 
  mutate(OD = as.numeric(OD)) %>% 
  filter(!Strain %in% "NBC") %>% 
  filter(!Replicate %in% NA) %>% 
  ggplot(aes(x = Strain, y = OD)) +
  geom_bar(aes(fill = Treatment), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_errorbar(stat = "summary", position= "dodge", width=0.25) +
  geom_jitter(width=0.1) +
  theme_bw() +
  theme(strip.background = element_rect(color = NULL, fill= "white", linetype="solid"), strip.text.x = element_text(size = 16/.pt, margin = margin(1, 1, 1, 1)), strip.text.y = element_text(size = 16/.pt, margin = margin(1, 1, 1, 1)))+
  theme(axis.text.x=element_text(size = 16/.pt, angle = -90, hjust = 0, vjust = 0.5),
        axis.text.y=element_text(size = 16/.pt),
        axis.title = element_text(size = 16/.pt)) +
  facet_grid(Treatment ~ Condition) +
  scale_fill_manual(values = c("cornflowerblue", "maroon")) + 
  labs(x = " ",
        y = "OD 600",
        title = "",
        caption = "")

anaerobicBacFigS.10

# ggsave(plot = anaerobicBacFigS.10,  filename = "anaerobicBacFigS.10.pdf", width = 6.6, height = 6, dpi = 300, scale = 1, units = "cm")
# # 
# ggsave(plot = anaerobicBacFigS.10,  filename = "anaerobicBacFigS.10.svg", width = 6.6, height = 6, dpi = 300, scale = 1, units = "cm")
```

```{r, warning=F, echo=F, message=F, include=F}
data_met <- readxl::read_excel("Input/20210329_MH_LT_Quantif.xlsx", sheet = 1)
data_met %>% colnames()
colnames(data_met) <- c("#", "Name", "Type", "Std_Conc", "RT", "Area", "ng_mL", "Compound", "Strain", "Treatment", "Condition", "Replicate")

data_met %>% typeof()
data_met <- data_met %>% as.data.frame()

data_met$Treatment <- factor(data_met$Treatment, levels=c("D","500"))

data_met$Treatment <- gsub("500", "MBOA", data_met$Treatment)
data_met$Treatment <- gsub("D", "DMSO", data_met$Treatment)

data_met$Name <- gsub("500", "MBOA", data_met$Name)
data_met$Name <- gsub("D", "DMSO", data_met$Name)
```

```{r, warning=F, echo=F, message=F, include=F}
mol <- read_excel("Input/Molecular_weight_BXDs.xlsx")


data_met <- left_join(data_met, mol, by = "Compound")
data_met %<>% mutate(M = as.numeric(M))

data_met$uMol <- ((data_met$ng_mL) / data_met$M) / 0.02
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  ggplot(aes(x = interaction(Strain, Treatment), y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Compound~Condition) + 
  labs(x = " ",
        y = "OD 600",
        title = "",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "MBOA") %>% 
  ggplot(aes(x = Strain, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  scale_fill_manual(values = "darkblue") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Condition~Treatment) + 
  labs(x = " ",
        y = "uMol",
        title = "MBOA",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "AMPO") %>% 
  ggplot(aes(x = Strain, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  scale_fill_manual(values = "darkred") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Condition~Treatment) + 
  labs(x = " ",
        y = "uMol",
        title = "AMPO",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "AAMPO") %>% 
  ggplot(aes(x = Strain, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  scale_fill_manual(values = "firebrick1") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Condition~Treatment) + 
  labs(x = " ",
        y = "uMol",
        title = "AAMPO",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "MHPA") %>% 
  ggplot(aes(x = Strain, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  scale_fill_manual(values = "gold2") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Condition~Treatment) + 
  labs(x = " ",
        y = "uMol",
        title = "MHPA",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  ggplot(aes(x = Strain, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean) +
  geom_jitter(width=0.1) +
  scale_fill_manual(values = c("firebrick1", "darkred", "darkblue", "gold2")) + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(Condition~Treatment) + 
  labs(x = " ",
        y = "uMol",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
anaerobicFigS.10met <- data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Treatment %in% "MBOA") %>% 
  ggplot(aes(x = Strain, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean) +
  scale_fill_manual(values = c("firebrick1", "darkred", "darkblue", "maroon")) + 
  theme_bw() +
  theme(strip.background = element_rect(color = NULL, fill= "white", linetype="solid"), strip.text.x = element_text(size = 16/.pt, margin = margin(1, 1, 1, 1)))+
  theme(axis.text.x=element_text(size = 16/.pt, angle = -90, hjust = 0, vjust = 0.5),
        axis.text.y=element_text(size = 16/.pt),
        axis.title = element_text(size = 16/.pt)) +
  facet_wrap(~ Condition) +
  labs(x = " ",
       y = "concentration [µMol]")

anaerobicFigS.10met

# ggsave(plot = anaerobicFigS.10met, filename = "anaerobicFigS.10met.pdf",width = 8.8, height = 6, dpi = 300, scale = 1, units = "cm")
# 
# ggsave(plot = anaerobicFigS.10met, filename = "anaerobicFigS.10met.svg", width = 8.8, height = 6, dpi = 300, scale = 1, units = "cm")
```

```{r, warning=F, echo=F, message=F}
anaerobicDMSOFigS.10 <- data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Treatment %in% "DMSO") %>% 
  ggplot(aes(x = interaction(Replicate, Strain), y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean) +
  scale_fill_manual(values = c("firebrick1", "darkred", "darkblue", "maroon")) + 
  theme_bw() +
  ylim(0,500)+
  theme(strip.background = element_rect(color = NULL, fill= "white", linetype="solid"), strip.text.x = element_text(size = 16/.pt, margin = margin(1, 1, 1, 1)))+
  theme(axis.text.x=element_text(size = 16/.pt, angle = -90, hjust = 0, vjust = 0.5),
        axis.text.y=element_text(size = 16/.pt),
        axis.title = element_text(size = 16/.pt)) +
  facet_wrap(~ Condition) +
  labs(x = " ",
       y = "concentration [µMol]")

anaerobicDMSOFigS.10

#ggsave(plot = anaerobicDMSOFigS.10,  filename = "anaerobicDMSOFigS.10.pdf",width = 8.8, height = 6, dpi = 300, scale = 1, units = "cm")

#ggsave(plot = anaerobicDMSOFigS.10,  filename = "anaerobicDMSOFigS.10.svg", width = 8.8, height = 6, dpi = 300, scale = 1, units = "cm")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "AMPO") %>% 
  filter(Treatment %in% "MBOA") %>% 
  ggplot(aes(x = Condition, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  stat_compare_means(method = "t.test", aes(x = Condition, y = uMol), label.y = 150, label.x = 1) +
  scale_fill_manual(values = "darkred") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~Strain) + 
  labs(x = " ",
        y = "uMol",
        title = "AMPO",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "MBOA") %>% 
  filter(Treatment %in% "MBOA") %>% 
  ggplot(aes(x = Condition, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  stat_compare_means(method = "t.test", aes(x = Condition, y = uMol), label.y = 550, label.x = 1) +
  scale_fill_manual(values = "darkblue") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~Strain) + 
  labs(x = " ",
        y = "uMol",
        title = "MBOA",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "AAMPO") %>% 
  filter(Treatment %in% "MBOA") %>% 
  ggplot(aes(x = Condition, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  stat_compare_means(method = "t.test", aes(x = Condition, y = uMol), label.y = 5, label.x = 1) +
  scale_fill_manual(values = "firebrick1") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~Strain) + 
  labs(x = " ",
        y = "uMol",
        title = "AAMPO",
        caption = "")
```

```{r, warning=F, echo=F, message=F}
data_met %>% 
  filter(!Strain %in% c("Blank", "Std", "Pool" )) %>%  
  filter(Compound %in% "MHPA") %>% 
  filter(Treatment %in% "MBOA") %>% 
  ggplot(aes(x = Condition, y = uMol)) +
  geom_bar(aes(fill = Compound), stat = "summary", fun.y = mean,  show.legend = FALSE) +
  geom_jitter(width=0.1) +
  stat_compare_means(method = "t.test", aes(x = Condition, y = uMol), label.y = 5, label.x = 1) +
  scale_fill_manual(values = "gold2") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(~Strain) + 
  labs(x = " ",
        y = "uMol",
        title = "MHPA",
        caption = "")
```

```{r}
sessionInfo()
```


